Deviab\DatabaseBundle\Entity\BorrowerContactNumbers:
    type: entity
    table: borrower_contact_numbers
    indexes:
        fk_borrower_id_idx:
            columns:
                - borrower_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contactNumber:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: contact_number
    manyToOne:
        borrower:
            targetEntity: BorrowerDetails
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                borrower_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
