Deviab\DatabaseBundle\Entity\BorrowerFamilyDetails:
    type: entity
    table: borrower_family_details
    indexes:
        fk_borrower_id_idx:
            columns:
                - borrower_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        relation:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        dob:
            type: date
            nullable: false
            comment: ''
        gender:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
    manyToOne:
        borrower:
            targetEntity: BorrowerDetails
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                borrower_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
