Deviab\DatabaseBundle\Entity\BorrowerDocuments:
    type: entity
    table: borrower_documents
    indexes:
        fk_borrower_id_idx:
            columns:
                - borrower_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        docUrl:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: doc_url
    manyToOne:
        borrower:
            targetEntity: BorrowerDetails
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                borrower_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
