Deviab\DatabaseBundle\Entity\LenderDetails:
    type: entity
    table: lender_details
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fname:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        lname:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        address:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        gender:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        dob:
            type: date
            nullable: true
            comment: ''
        primaryMobileNumber:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: primary_mobile_number
        profilePic:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: profile_pic
        googleId:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: google_id
        facebookId:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: facebook_id
    oneToOne:
        currentStatus:
            targetEntity: Deviab\RepaymentBundle\Entity\LenderCurrentStatus
            cascade: {  }
            mappedBy: lender
        wallet:
            targetEntity: Deviab\RepaymentBundle\Entity\LenderWallet
            cascade: {  }
            mappedBy: lender
    oneToMany:
        fromLenderTransactions:
            targetEntity: Deviab\TransactionBundle\Entity\LenderDeviabTransaction
            mappedBy: lender
        toLenderTransactions:
            targetEntity: Deviab\TransactionBundle\Entity\DeviabLenderTransaction
            mappedBy: lender
    lifecycleCallbacks: {  }
