Deviab\DatabaseBundle\Entity\Project:
    type: entity
    table: projects
    indexes:
        fk_district_id_idx:
            columns:
                - district_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
    fields:
        pName:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: p_name

        amountRaised:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: amount_raised
        capitalAmount:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: capital_amount
        returnedAmount:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: returned_amount
        description:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''

    manyToOne:
        district:
            targetEntity: MasterDistrict
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                district_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        borrowers:
            targetEntity: BorrowerDetails
            mappedBy: project



