fabric:
    resource: "@FabricBundle/Resources/config/routing.yml"
    prefix:   /

deviab_borrower:
    resource: "@DeviabBorrowerBundle/Resources/config/routing.yml"
    prefix:    /borrowers
    type:      rest

deviab_app:
    resource: "@DeviabAppBundle/Resources/config/routing.php"
    prefix:   /
