deviab_user:
    resource: "@DeviabUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

deviab_app:
    resource: @DeviabAppBundle/Controller/
    type:     annotation

