deviab_repayment:
    resource: "@DeviabRepaymentBundle/Resources/config/routing.yml"
    prefix:   /

fabric:
    resource: "@FabricBundle/Resources/config/routing.yml"
    prefix:   /

deviab_admin:
    resource: "@DeviabBorrowerBundle/Resources/config/routing_admin.yml"
    prefix:    api/v1/{role}
    type:      rest

deviab_borrower:
    resource: "@DeviabBorrowerBundle/Resources/config/routing.yml"
    prefix:    api/v1/borrowers
    type:      rest

# Login Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# fos_user_profile:
#     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#     prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

# fos_user_resetting:
#     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#     prefix: /resetting

# fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: /profile
