deviab_app_routing:
    resource: "@DeviabAppBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

deviab_app:
    resource: @DeviabAppBundle/Controller/
    type:     annotation