deviab_repayment:
    resource: "@DeviabRepaymentBundle/Resources/config/routing.yml"
    prefix:    api/v1/{authToken}/repayment
    type:      rest

fabric:
    resource: "@FabricBundle/Resources/config/routing.yml"
    prefix:   /

deviab_app:
    resource: "@DeviabAppBundle/Resources/config/routing.php"
    prefix:   /

deviab_admin:
    resource: "@DeviabBorrowerBundle/Resources/config/routing_admin.yml"
    prefix:    api/v1/{authToken}/operation
    type:      rest

deviab_borrower:
    resource: "@DeviabBorrowerBundle/Resources/config/routing.yml"
    prefix:    api/v1/borrowers
    type:      rest

deviab_transaction:
    resource: "@DeviabTransactionBundle/Resources/config/routing.yml"
    prefix:   api/v1/{authToken}/transaction
    type:      rest
