get_lender_investment:
    pattern:  lenders/{lenderId}
    defaults: { _controller: DeviabTransactionBundle:Investment:getLenderInvestment}
    requirements:
        _method: GET
        lenderId: "\d+"
