get_lender_investment:
    pattern:  lenders/{lenderId}
    defaults: { _controller: DeviabTransactionBundle:Investment:getLenderInvestment}
    requirements:
        _method: GET
        lenderId: "\d+"

get_deviab_transaction:
    pattern:  deviabtransaction/{lenderId}
    defaults: { _controller: DeviabTransactionBundle:Investment:getDeviabTransactionDetails}
    requirements:
        _method: GET
        lenderId: "\d+"

get_lender_transaction:
    pattern:  lenderstransaction/{lenderId}
    defaults: { _controller: DeviabTransactionBundle:Investment:getLenderTransactionDetails}
    requirements:
        _method: GET
        lenderId: "\d+"

