get_lender_investment:
    pattern:  lenders/{lenderId}
    defaults: { _controller: DeviabTransactionBundle:Investment:getLenderInvestment}
    requirements:
        _method: GET
        lenderId: "\d+"

get_transaction_form_data:
    pattern:  /{lenderId}/fd
    defaults: { _controller: DeviabTransactionBundle:Transaction:transaction}
    requirements:
        _method: GET
        lenderId: "\d+"

payu_success_webhook:
    pattern:  /webhook/success
    defaults: { _controller: DeviabTransactionBundle:Transaction:payuSuccessWebhook}
    requirements:
        _method: GET


get_wallet:
    pattern:  /{lenderId}/wallet
    defaults: { _controller: DeviabTransactionBundle:Investment:getWallet}
    requirements:
        _method: GET
        lenderId: "\d+"



