<?php

namespace Deviab\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Borrower_Fin_DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Borrower_Fin_DetailRepository extends EntityRepository
{
}
