<?php

namespace Deviab\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Lending_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lending_detailRepository extends EntityRepository
{
}
