<?php

namespace Deviab\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LendingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LendingDetailRepository extends EntityRepository
{
}
