<?php

namespace Deviab\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Loan_PurposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Loan_PurposeRepository extends EntityRepository
{
}
