<?php

namespace Deviab\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoanPurposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanPurposeRepository extends EntityRepository
{
}
