add_loan_ops_strategy:
    pattern:  /{adminId}/new-loan-ops-strategy
    defaults: { _controller: DeviabBorrowerBundle:OpsStrategy:newLoanOpsStrategy}
    requirements:
        _method: POST
        adminId: "\d+"

update_loan_ops_strategy:
    pattern:  /{adminId}/{loanOpsId}/update-loan-ops-strategy
    defaults: { _controller: DeviabBorrowerBundle:OpsStrategy:updateLoanOpsStrategy}
    requirements:
        _method: POST
        adminId: "\d+"

get_loan_ops_strategy:
    pattern:  /{adminId}/loan-ops-strategy/{loanOpsId}
    defaults: { _controller: DeviabBorrowerBundle:OpsStrategy:getLoanOpsStrategy}
    requirements:
        _method: GET
        adminId: "\d+"
        loanOpsId: "\d+"

get_all_loan_ops_strategy:
    pattern:  /{adminId}/loan-ops-strategy
    defaults: { _controller: DeviabBorrowerBundle:OpsStrategy:getAllLoanOpsStrategy}
    requirements:
        _method: GET
        adminId: "\d+"