get_project_status:
    pattern:  /{projectId}
    defaults: { _controller: DeviabBorrowerBundle:Project:getProject}
    requirements:
       _method: GET
       projectId: "\d+"

get_featured_project:
    pattern:  featured-project/{projectId}
    defaults: { _controller: DeviabBorrowerBundle:Project:getFeaturedProject}
    requirements:
       _method: GET
       projectId: "\d+"